version: "3.7"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./sac-widget/:/var/www/html/"
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      - ALLOW_OVERRIDE=true
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: "${DB_HOSTNAME}"
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5000:80"
volumes:
  mysql-data:
